services:
  - type: web
    name: label-generator
    runtime: docker
    plan: starter
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health